import { Template } from 'meteor/templating';
import { Meteor } from 'meteor/meteor';
import '../imports/ui/calendar/calendar.js';
import '../imports/ui/collections/user_accounts.js';
import '../imports/ui/signin/signin.js';
import '../imports/ui/signup/signup.js';
import '../imports/ui/budgetsetup/budgetsetup.js';
import '../imports/ui/dashboard/dashboard.js';
import '../imports/ui/signup/upload.js';
import '../routes/signin.js';
